# Publish new map
map_update_interval: 0.5
maxUrange: 5.5
maxRange: 6.1
particles: 100

minimumScore: 50
srr: 0.1
srt: 0.2
str: 0.1
stt: 0.2

# Update frequencies
linearUpdate: 0.3
angularUpdate: 0.5
temporalUpdate: 2.0
resampleThreshold: 0.5

# Inital Map Size
xmin: -100.0
ymin: -100.0
xmax: 100.0
ymax: 100.0
delta: 0.05

# All default
sigma: 0.05
kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 5
lsigma: 0.075
ogain: 3.0
lskip: 0
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005